version: "2"
services:
    app:
        container_name: app
        image: 0980121931/chat-room-api-image
        restart: always
        build: .
        links:
            - mongo
    mongo:
        container_name: mongo
        image: 0980121931/mongo
        volumes:
        - ./data:/data/db
        command: mongod --noauth

